-- MySQL Script generated by MySQL Workbench
-- недеља, 10. децембар 2017. 23:34:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klijent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klijent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klijent` (
  `key_klijent` INT NOT NULL,
  `ime` VARCHAR(100) NOT NULL,
  `prezime` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `kontakt_telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`key_klijent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fizicko_lice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fizicko_lice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fizicko_lice` (
  `klijent_key_klijent` INT NOT NULL,
  `jmbg` VARCHAR(13) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `broj_registracija` INT NOT NULL DEFAULT 0,
  INDEX `fk_fizicko_lice_klijent_idx` (`klijent_key_klijent` ASC),
  PRIMARY KEY (`klijent_key_klijent`),
  CONSTRAINT `fk_fizicko_lice_klijent`
    FOREIGN KEY (`klijent_key_klijent`)
    REFERENCES `mydb`.`klijent` (`key_klijent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`firma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`firma` (
  `key_firma` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `PIB` VARCHAR(45) NOT NULL,
  `broj_racuna` VARCHAR(45) NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `internet_adresa` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `kontakt_telefon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`key_firma`),
  UNIQUE INDEX `PIB_UNIQUE` (`PIB` ASC),
  UNIQUE INDEX `broj_racuna_UNIQUE` (`broj_racuna` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pravno_lice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pravno_lice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pravno_lice` (
  `klijent_key_klijent` INT NOT NULL,
  `firma_key_firma` INT NOT NULL,
  INDEX `fk_pravno_lice_klijent1_idx` (`klijent_key_klijent` ASC),
  PRIMARY KEY (`klijent_key_klijent`),
  INDEX `fk_pravno_lice_firma1_idx` (`firma_key_firma` ASC),
  CONSTRAINT `fk_pravno_lice_klijent1`
    FOREIGN KEY (`klijent_key_klijent`)
    REFERENCES `mydb`.`klijent` (`key_klijent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pravno_lice_firma1`
    FOREIGN KEY (`firma_key_firma`)
    REFERENCES `mydb`.`firma` (`key_firma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`smestaj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`smestaj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`smestaj` (
  `key_smestaj` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  `grad` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`key_smestaj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registracija_smestaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registracija_smestaja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registracija_smestaja` (
  `pravno_lice_klijent_key_klijent` INT NOT NULL,
  `smestaj_key_smestaj` INT NOT NULL,
  `datum_registracije` DATE NOT NULL,
  PRIMARY KEY (`pravno_lice_klijent_key_klijent`, `smestaj_key_smestaj`),
  INDEX `fk_registracija_smestaja_smestaj1_idx` (`smestaj_key_smestaj` ASC),
  INDEX `fk_registracija_smestaja_pravno_lice1_idx` (`pravno_lice_klijent_key_klijent` ASC),
  CONSTRAINT `fk_registracija_smestaja_pravno_lice1`
    FOREIGN KEY (`pravno_lice_klijent_key_klijent`)
    REFERENCES `mydb`.`pravno_lice` (`klijent_key_klijent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registracija_smestaja_smestaj1`
    FOREIGN KEY (`smestaj_key_smestaj`)
    REFERENCES `mydb`.`smestaj` (`key_smestaj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ponuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ponuda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ponuda` (
  `key_ponuda` INT NOT NULL,
  `registracija_smestaja_pravno_lice_klijent_key_klijent` INT NOT NULL,
  `registracija_smestaja_smestaj_key_smestaj` INT NOT NULL,
  `tip_sobe` VARCHAR(45) NOT NULL,
  `broj_soba` INT NOT NULL,
  `aktivna` TINYINT NOT NULL,
  `cena_sobe` DOUBLE NOT NULL,
  `datum_pocetka` DATE NOT NULL,
  `datum_zavrsetka` DATE NOT NULL,
  PRIMARY KEY (`key_ponuda`),
  INDEX `fk_ponuda_registracija_smestaja1_idx` (`registracija_smestaja_pravno_lice_klijent_key_klijent` ASC, `registracija_smestaja_smestaj_key_smestaj` ASC),
  CONSTRAINT `fk_ponuda_registracija_smestaja1`
    FOREIGN KEY (`registracija_smestaja_pravno_lice_klijent_key_klijent` , `registracija_smestaja_smestaj_key_smestaj`)
    REFERENCES `mydb`.`registracija_smestaja` (`pravno_lice_klijent_key_klijent` , `smestaj_key_smestaj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `key_status` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`key_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezervacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rezervacija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rezervacija` (
  `ponuda_key_ponuda` INT NOT NULL,
  `fizicko_lice_klijent_key_klijent` INT NOT NULL,
  `status_key_status` INT NOT NULL,
  `datum_rezervacije` DATE NOT NULL,
  `koliko_soba` INT NOT NULL,
  `tip_soba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ponuda_key_ponuda`, `fizicko_lice_klijent_key_klijent`),
  INDEX `fk_rezervacija_fizicko_lice1_idx` (`fizicko_lice_klijent_key_klijent` ASC),
  INDEX `fk_rezervacija_ponuda1_idx` (`ponuda_key_ponuda` ASC),
  INDEX `fk_rezervacija_status1_idx` (`status_key_status` ASC),
  CONSTRAINT `fk_rezervacija_ponuda1`
    FOREIGN KEY (`ponuda_key_ponuda`)
    REFERENCES `mydb`.`ponuda` (`key_ponuda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rezervacija_fizicko_lice1`
    FOREIGN KEY (`fizicko_lice_klijent_key_klijent`)
    REFERENCES `mydb`.`fizicko_lice` (`klijent_key_klijent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rezervacija_status1`
    FOREIGN KEY (`status_key_status`)
    REFERENCES `mydb`.`status` (`key_status`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faktura_rezervacije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`faktura_rezervacije` ;

CREATE TABLE IF NOT EXISTS `mydb`.`faktura_rezervacije` (
  `rezervacija_ponuda_key_ponuda` INT NOT NULL,
  `rezervacija_fizicko_lice_klijent_key_klijent` INT NOT NULL,
  `suma` DOUBLE NOT NULL DEFAULT 0,
  `placena_faktura` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`rezervacija_ponuda_key_ponuda`, `rezervacija_fizicko_lice_klijent_key_klijent`),
  CONSTRAINT `fk_table1_rezervacija1`
    FOREIGN KEY (`rezervacija_ponuda_key_ponuda` , `rezervacija_fizicko_lice_klijent_key_klijent`)
    REFERENCES `mydb`.`rezervacija` (`ponuda_key_ponuda` , `fizicko_lice_klijent_key_klijent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
